### ISSUE TITLE
Idea: make another plugin type: Indexer

### ISSUE THREAD

**Issue by appetizermonster** [hainproject/hain#190]
I eventually have thinking about two types of plugin for the next version.
one is Commander, the other is Indexer.

Commander is a type of plugin like existing plugins.
it must have prefix.
querying with prefix will only show matched plugin's result.
a plugin without prefix will not be permitted.
any existing plugins with prefix will works without any modification.
and `Hain` will make user to choose one prefix if prefix duplication has occured.

Indexer is a new type of plugin.
it should returns results immediately, items of which should have primary and secondary matching string.
`Hain` will sorts and shows unified results of indexers.
one example of Indexer is `hain-plugin-filesearch`, `hain-plugin-url`.

**Comment by staff0rd** [comment]
Would this eliminate the delay in typing too fast?  I think the application needs to be optimised for touch typing.  Often I am able to type and hit enter prior to a plugin's result being available (even though the result is not coming from the network).  This means I often execute unintended things...

I was considering opening another issue, but this one and possibly #180 also kind of hint at it.  I think there needs to be some kind of

**Comment by malipetek** [comment]
It would be nice if user could change the prefix default. I have changed mine locally to **"<"** because for **"/"** I need to press shift key.

For fast launch it seems I can launch before loading results for the first letter. For ex. I use **Franz messenger app** and I open it by this combo: `alt+space+f+r+enter`, works well.

But for example for **"chrome"**, I type "c" first of items is **3ds max's** "change graphics mode". Therefore I write chrome and first result is **"chrome dev editor"**. It may be a users frequent opened apps and weighting accordingly.

Or another option may be user defined fast launch keywords with a default **suffix**. For example user wants to lauch filezilla very fast he can define 3 letters "flz". Afterwards when he opens **Hain** he uses this combo to deploy app: `alt+space+flz+.+.+enter`. In example **search** starts to search for "flz." keyword. After en of string gets two dots search plugin cancels and another plugin brings in user defined launcher.

**Comment by staff0rd** [comment]
My issue is more related to how quickly the results come back for same phrase, but parsed by two separate plugins.  For example, if i type _reddit.com_, the Files & Folders plugin matches this with "GIMP 2", but the Links plugin matches this as a url.  It is sometimes (not always) possible for me to type reddit.com and hit enter and have it open GIMP - even though GIMP does not appear in the list until i type the full phrase (ie; it doesn't appear until i type the m at the end).  I suspect there's some kind of async pattern matching going on there.

I actually wrote plugin that does just what you're asking the other day, checkout [hpm-plugin-keywords](https://github.com/staff0rd/hain-plugin-keywords) via /hpm.  It allows keywords to be configured (without prefixes) to launch urls (with query pass-through) and files of your choice.  It does not however solve the speed problem due to the async issue above.

**Comment by malipetek** [comment]
I was not able to reach staff0rd 's keywords plugin's preferences panel. But I did used another plugin called "shortcuts" and it is very satisfying about all the stuff I suggested above. Hain is very promising.

**Comment by staff0rd** [comment]
Actually my plugin is based on, and extends, the shortcuts plugin.  Are you saying that preferences does not appear for the plugin?

![image](https://cloud.githubusercontent.com/assets/6289998/19137910/47f86f0a-8bc3-11e6-81e9-d77d4e3a462a.png)

**Comment by malipetek** [comment]
No, was expecting a separate prefs. called keywords. I didn't know a plugin can depend on another.

**Comment by staff0rd** [comment]
It doesn't depend on shortcuts, it's pretty much a replacement for it.  Will look into it further on the [issue you opened](https://github.com/staff0rd/hain-plugin-keywords/issues/2).

**Comment by Gooseman616** [comment]
It would be great if it would be possible to pass one plugin's result as an argument to another plugin.

**Comment by appetizermonster** [comment]
@Gooseman616 that would be great, but i dont have any idea how to implement it beautifully in the current architecture.

**Comment by cpriest** [comment]
@Gooseman616 I believe you could use node IPC modules to achieve that effect or possibly the process EventEmitter.

**Comment by Gooseman616** [comment]
@appetizermonster
Yeah. So do I :)
But maybe one day... :D

**Comment by cpriest** [comment]
This has been completed by Heejin, it's not well documented at the moment, but looking at hain-plugin-filesearch shows its usage.

As for the speed issue, it is slightly faster with the indexer, after the first search.  Is there another ticket regarding the speed?  @staff0rd I experience the same thing, I intend to take care of it soon.
