### ISSUE TITLE
[Theme Request] Add shadow to Hain window so it doesn't blend into a white screen...

### ISSUE THREAD

**Issue by jasondavis** [hainproject/hain#232]
## Current Hain window blends into white screen as it has no shadow or border!

![hain-app-no-shadow](https://cloud.githubusercontent.com/assets/186818/24983768/5bef0252-1fb7-11e7-99e9-8778dcae4356.png)

## Proposed Shadow added...
![hain-app-dropshaddow](https://cloud.githubusercontent.com/assets/186818/24983765/57dd5be6-1fb7-11e7-922a-3a82911e8f0f.png)

**Comment by cpriest** [comment]
That would be a nice addition.

I wonder if you would be interested in looking into making that happen?  
I'd be happy to help show you the ropes.

**Comment by jasondavis** [comment]
@cpriest I cvould look into, i'm pretty familiar with ElectronJS.

Also I saw this site http://www.packal.org/  

> Packal (beta) puts Alfred Workflows and Themes at your fingertips.

It seems to be a currated list of workflows and themes for Alfred.

I just discovered Alfred and Hain.  Actually I have known of Alfred for years but as a Windows user I never explored it too much.  I realy Hain isn't really the exact same but in a way similar to how the developer of the edotro SublimeText made all the plugins and themes usre the Mac versions of TextMate editor plugins and themes was genius!

I don't think it would be the same as I havent seen the word "Workflow" anywere with Hain yet however I think pretty much the same tasks are possibble through Hain Plugins.

So perhaps this website can be of use for inspiration in bnew Hain Plugins and maybe Hain could have a site where users can share there plugins and stuff someday.  Sublimetext has a similar site for there plugins too.

**Comment by cpriest** [comment]
That is interesting, I'd have to dig into the code that handles the 
current theme, but at least the one alfred theme I'm looking at seems 
pretty verbose, I'm sure we could be compatible with these themes.

I'm working, personally, on a deep windows integration plugin now for 
hain and have a number of minor fixes & tweaks to work on after that, 
but themeing has been a frequent request.

Right now, npmjs.org is where hain plugins are hosted.  Right from hain 
you can type /hpm ... to list plugins already published by others to 
npmjs.  I would expect that to stay the same since it's already available.

What the project really needs is additional contributors.  Heejin 
(original author) doesn't have a lot of free time, nor do I, but we're 
doing our best.  Any contributions are very welcome.

-Clint

**Comment by aouerfelli** [comment]
What OS are you using? I'm on Windows 10 and the shadow is showing up for me (on v0.6.2):
![image](https://cloud.githubusercontent.com/assets/11808979/25130323/c42bb21e-240f-11e7-9ed4-d5f06d93f4a5.png)

**Comment by cpriest** [comment]
Come to think of it, I just checked and mine has a shadow as well.
