### ISSUE TITLE
Really high CPU usage.

### ISSUE THREAD

**Issue by Tatrii** [hainproject/hain#255]
I've read thru the other issues that seem to have the same problem I am but that didn't really help. I love this software but it using 25 to 40% CPU in the background is kind of extreme. I don't have the most powerful PC in the world but it's decent. The program uses more than a program like adobe premiere pro would use while editing.

Windows 10 64 bit  Version 1709
Intel Core i5 4430 @ 3.00Ghz
16GB Ram
Nvidia Geforce GTX 970

**Comment by kbuckleys** [comment]
That's the primary reason I stopped using Hain. Your rig is definitely not to blame here, and I'm guessing the issue has to do with Electron itself. I've had similar CPU issues with other Electron-based apps like Brave Browser and Kaku.

**Comment by Tatrii** [comment]
@kbuckleys Now that you mention it I have noticed high CPU usage on brave when I've used it (wasn't aware it was electron based). It's unfortunate because this has been my favorite launcher so far, I guess I'll have to keep looking!

**Comment by caioac** [comment]
@kbuckleys What are you using now?

**Comment by albzn540** [comment]
Same on my computer, has anyone figured out a solution for this?  
![Processor usage](https://i.gyazo.com/9ab047b675a1ac269229cebcf0fdd4dd.png)

**Comment by Tatrii** [comment]
@albzn540 I was never able to figure it out, I ended up switching back to Launchy.

**Comment by albzn540** [comment]
@Tatrii Ah okay, too bad. Hain was very aesteticly pleasing

**Comment by alanaasmaa** [comment]
This issue kept me away from Hain for a while. Then i finally gave it a change. 
I didn't notice almost any CPU usage when not using. Then i thought maybe it's because i don't have any plugins. Then i installed a bunch of plugins that i would use and still the usage is same.

When i open hain it uses about 2,5% for once and then goes back to 0%

I used Wox before and even the memory usage seems to be about same ~150MB.

Could you maybe paste a list of plugins you use? 
And i know this issue is almost a year old, but if this is outdated i feel it should be closed so it would not push users like me away.

**Comment by Tatrii** [comment]
@alanaasmaa You're so right! I do need to close this. I re-downloaded Hain about 3 months ago and it's been working flawlessly since!
